sudo: true
language: node_js
os:
  - linux
  - osx
before_script:
  - npm install
  - node lib/install.js
node_js:
  - '6'
  - '5'
  - '4'
addons:
  apt:
    packages:
      - libpng-dev
      - zlib1g-dev
